ls ~/1kGP/|grep "cram$"|perl -npe "s/.final.cram//" |xargs -I{}  -P 20 bash get_nonAFR_BK_each.sh {}
cat sample_info_1kGP.txt|grep -v "AFR"|while read sample pop;do  num1=`grep  -m 1 "$sample" sample_INS_count.tsv|cut -f1`;num2=`cat BKsArcInBAM_nonAFR/${sample}_dan.bed|wc -l ` ;echo -e "$sample\t$pop\t$num1\t$num2"|perl -F'\t' -alne '$rate=$F[4]/$F[3];print "$F[0]\t$F[1]\t$F[2]\t$F[4]\t$F[3]\tdan";';done >share_rate_nonAFR_1kGP.bed
cat sample_info_1kGP.txt|grep -v "AFR"|while read sample pop;do  num1=`grep -m 1 "$sample" sample_INS_count.tsv|cut -f1`;num2=`cat BKsArcInBAM_nonAFR/${sample}_Altai.bed|wc -l ` ;echo -e "$sample\t$pop\t$num1\t$num2"|perl -F'\t' -alne '$rate=$F[4]/$F[3];print "$F[0]\t$F[1]\t$F[2]\t$F[4]\t$F[3]\tAltai";';done >>share_rate_nonAFR_1kGP.bed
cat sample_info_1kGP.txt|grep -v "AFR"|while read sample pop;do  num1=`grep  -m 1 "$sample" sample_INS_count.tsv|cut -f1`;num2=`cat BKsArcInBAM_nonAFR/${sample}_Vindija.bed|wc -l ` ;echo -e "$sample\t$pop\t$num1\t$num2"|perl -F'\t' -alne '$rate=$F[4]/$F[3];print "$F[0]\t$F[1]\t$F[2]\t$F[4]\t$F[3]\tVindija";';done >>share_rate_nonAFR_1kGP.bed

ls ~/1kGP/|grep "cram$"|grep "HGDP"|perl -npe "s/\..*//"|xargs -I{}  -P 20 bash get_nonAFR_BK_each_HGDP.sh {}
ls ~/region_bam_sort/|grep "bam$"|grep "HGDP"|perl -npe "s/\..*//"|xargs -I{}  -P 20 bash get_nonAFR_BK_each_HGDP.sh {}
cat ../sgdp_HGDP_sample.txt sample_info_HGDP.txt|sort|uniq|while read sample pop;do  num1=`grep  -m 1 "$sample" sample_INS_count_HGDP.tsv|cut -f1`;num2=`cat BKsArcInBAM_nonAFR/${sample}_dan.bed|wc -l ` ;echo -e "$sample\t$pop\t$num1\t$num2"|perl -F'\t' -alne '$rate=$F[4]/$F[3];print "$F[0]\t$F[1]\t$F[2]\t$F[4]\t$F[3]\tdan";';done >share_rate_nonAFR_HGDP.bed
cat ../sgdp_HGDP_sample.txt sample_info_HGDP.txt|sort|uniq|while read sample pop;do  num1=`grep -m 1 "$sample" sample_INS_count_HGDP.tsv|cut -f1`;num2=`cat BKsArcInBAM_nonAFR/${sample}_Altai.bed|wc -l ` ;echo -e "$sample\t$pop\t$num1\t$num2"|perl -F'\t' -alne '$rate=$F[4]/$F[3];print "$F[0]\t$F[1]\t$F[2]\t$F[4]\t$F[3]\tAltai";';done >>share_rate_nonAFR_HGDP.bed
cat ../sgdp_HGDP_sample.txt sample_info_HGDP.txt|sort|uniq|while read sample pop;do  num1=`grep  -m 1 "$sample" sample_INS_count_HGDP.tsv|cut -f1`;num2=`cat BKsArcInBAM_nonAFR/${sample}_Vindija.bed|wc -l ` ;echo -e "$sample\t$pop\t$num1\t$num2"|perl -F'\t' -alne '$rate=$F[4]/$F[3];print "$F[0]\t$F[1]\t$F[2]\t$F[4]\t$F[3]\tVindija";';done >>share_rate_nonAFR_HGDP.bed
