#! /usr/bin/perl
$pad=50;
if(length($ARGV[0]) !=0)
{
	$pad=$ARGV[0];
}
while(<STDIN>)
{
	chomp();
	@F=split("\t",$_);
	$start=$F[1]-$pad;
	$end=$F[1]+$pad;
	$F[1]="$start\t$end";
	print join("\t",@F)."\n";
}
